[package]
name = "json2rust"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
syn-serde = { path = "../..", features = ["json"] }
syn = { version = "2", features = ["full"] }
prettyplease = "0.2"
quote = "1"

[lints]
workspace = true
